### ISSUE TITLE
Use a loop and a timeout on docker wait, upload intermediate logs

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/scheduler#62]
Seems like containers getting lost.
Assuming that it might be better to loop with a long timeout in containers.wait(timeout=(30 minutes))

then when the timeout happens, use archive endpoint to pull logs, and upload the logs to scheduler/latest/...

**Comment by ylyangtw** [comment]
this issue is marked as `Done`. should we close it?

**Comment by valentinedwv** [comment]
Not yet reviewed, or merged
